"""The Items & Money catalog the panel shows (PLAN C10).

``data/item_catalog_v05.json`` is generated by ``tools/gen_items_catalog.py``
from the finished v0.5 catalog; this module reads it (fail-closed: a damaged
file gives an empty catalog, never guessed rows) and turns it into the rows
of the item list:

* Listed rows: every ``default`` item and every ``opt-in`` item whose toggle
  is on. These fill the list, in the player's category order.
* Unlisted rows: excluded items, opt-in items whose toggle is off, and the
  currencies (added on the Money card). They carry a plain ``reason`` and are
  shown only while a search finds them, after the listed results, so they
  never clutter the list.

The installed game mod decides what can really be added. A v0.5 game mod
answers probes (services/item_probe.py); an older one (v0.3.x/v0.4.0, the
Live Add v3 route) can add only the items on its embedded allowlist
(services.item_policy.APPROVED_LIVE_ALIASES).
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
from pathlib import Path
import re
import sys
from typing import Iterable, Mapping

from models.catalog_filter import fold_text
from services.item_policy import APPROVED_LIVE_ALIASES
from services.item_probe import (
    CHIP_KINDS,
    CHIP_LABELS,
    CHIP_NEEDS_DLC,
    CHIP_NOT_AVAILABLE,
    auto_level_up_reason,
    is_auto_level_up_item,
)

CATALOG_FILE_NAME = "item_catalog_v05.json"
CATALOG_SCHEMA = "sb-panel-items-catalog/v1"
CATALOG_MAX_BYTES = 2 * 1024 * 1024
CATALOG_MAX_ROWS = 2000
GROUPS = ("default", "opt-in", "money", "excluded")
# Panel toggle keys; "currencies" lives on the Money card, the others under
# More items.
TOGGLE_KEYS = ("cores", "collectibles", "extras", "currencies")
MONEY_ALIAS = "BetaCrystal"
# A money add of this much or more is sent only after a second, explicit
# confirmation on the Money card, which lapses after MONEY_CONFIRM_SEC.
MONEY_CONFIRM_AT = 100_000
MONEY_CONFIRM_SEC = 30.0

_SAFE_ALIAS = re.compile(r"^[A-Za-z0-9_+]{1,128}$")
_CONTROL = re.compile(r"[\x00-\x1f\x7f]")


def _text(value: object, limit: int) -> str:
    return _CONTROL.sub("", str(value or "")).strip()[:limit]


def _flag(value: object) -> bool:
    return value is True


def _count(value: object) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError("not a whole number")
    if value < 0 or value > 1_000_000_000:
        raise ValueError("out of range")
    return value


@dataclass(frozen=True)
class Toggle:
    key: str
    name: str
    hint: str
    where: str
    count: int


@dataclass(frozen=True)
class PanelCatalog:
    rows: tuple[dict, ...] = ()
    category_order: tuple[str, ...] = ()
    toggles: tuple[Toggle, ...] = ()
    money: dict = field(default_factory=dict)
    source_sha256: str = ""
    error: str = ""

    def row(self, alias: str) -> dict | None:
        key = str(alias or "").lower()
        for row in self.rows:
            if row["alias"].lower() == key:
                return row
        return None

    def toggle(self, key: str) -> Toggle | None:
        return next((toggle for toggle in self.toggles if toggle.key == key), None)

    @property
    def currencies(self) -> list[dict]:
        """Gold first, then the opt-in shop currencies."""
        gold = self.row(MONEY_ALIAS)
        others = [row for row in self.rows if row["toggle"] == "currencies"]
        return ([gold] if gold else []) + others


def catalog_paths(mod_root: Path) -> list[Path]:
    """Where the catalog is read from: the copy bundled with this panel build
    first (it always matches the code), then the mod folder's data copy."""
    bundled = Path(getattr(sys, "_MEIPASS", "")) if getattr(sys, "frozen", False) else None
    paths = []
    if bundled is not None:
        paths.append(bundled / "data" / CATALOG_FILE_NAME)
    paths.append(Path(mod_root) / "data" / CATALOG_FILE_NAME)
    return paths


def _parse_row(raw: Mapping[str, object]) -> dict:
    alias = str(raw.get("alias") or "")
    if not _SAFE_ALIAS.fullmatch(alias):
        raise ValueError(f"unsafe item identifier {alias[:40]!r}")
    group = str(raw.get("group") or "")
    if group not in GROUPS:
        raise ValueError(f"{alias}: unknown group {group!r}")
    toggle = str(raw.get("toggle") or "")
    if group == "opt-in" and toggle not in TOGGLE_KEYS:
        raise ValueError(f"{alias}: unknown toggle {toggle!r}")
    if group != "opt-in" and toggle:
        raise ValueError(f"{alias}: toggle on a {group} row")
    name = _text(raw.get("name"), 160)
    category = _text(raw.get("category"), 64)
    if not name or not category:
        raise ValueError(f"{alias}: missing name or category")
    minimum = _count(raw.get("min"))
    maximum = _count(raw.get("max"))
    if group == "excluded":
        if minimum or maximum:
            raise ValueError(f"{alias}: an excluded row has a quantity")
    elif not 1 <= minimum <= maximum:
        raise ValueError(f"{alias}: bad quantity range")
    reason = _text(raw.get("reason"), 240)
    if group == "excluded" and not reason:
        raise ValueError(f"{alias}: an excluded row needs a reason")
    return {
        "alias": alias,
        "name": name,
        "category": category,
        "group": group,
        "toggle": toggle,
        "dlc": _flag(raw.get("dlc")),
        "reason": reason,
        "note": _text(raw.get("note"), 240),
        "min": minimum,
        "max": maximum,
        "one_copy": _flag(raw.get("one_copy")),
        "stat_capped": _flag(raw.get("stat_capped")),
        "quest": _flag(raw.get("quest")),
        "trophy": _flag(raw.get("trophy")),
        "description": _text(raw.get("description"), 240),
    }


def parse_catalog(data: bytes) -> PanelCatalog:
    """Validate the generated catalog; raise ValueError on anything off."""
    if len(data) > CATALOG_MAX_BYTES:
        raise ValueError("catalog file too large")
    document = json.loads(data.decode("utf-8"))
    if not isinstance(document, dict) or document.get("schema") != CATALOG_SCHEMA:
        raise ValueError("not a panel item catalog")
    items = document.get("items")
    if not isinstance(items, list) or not 0 < len(items) <= CATALOG_MAX_ROWS:
        raise ValueError("catalog has no item rows")
    rows = []
    seen: set[str] = set()
    names: set[str] = set()
    for raw in items:
        if not isinstance(raw, dict):
            raise ValueError("catalog row is not an object")
        row = _parse_row(raw)
        key = row["alias"].lower()
        if key in seen:
            raise ValueError(f"duplicate item {row['alias']}")
        if row["name"].casefold() in names:
            raise ValueError(f"duplicate item name {row['name']!r}")
        seen.add(key)
        names.add(row["name"].casefold())
        rows.append(row)
    order = tuple(_text(name, 64) for name in document.get("category_order") or [])
    if not order or any(row["category"] not in order for row in rows):
        raise ValueError("catalog category order is incomplete")
    toggles = []
    for raw in document.get("toggles") or []:
        if not isinstance(raw, dict) or raw.get("key") not in TOGGLE_KEYS:
            raise ValueError("bad toggle")
        toggles.append(Toggle(
            key=str(raw["key"]),
            name=_text(raw.get("name"), 40),
            hint=_text(raw.get("hint"), 200),
            where=_text(raw.get("where"), 40),
            count=_count(raw.get("count")),
        ))
    money_raw = document.get("money") or {}
    money = {
        "alias": MONEY_ALIAS,
        "name": _text(money_raw.get("name"), 40) or "Gold",
        "per_add_min": _count(money_raw.get("per_add_min")),
        "per_add_max": _count(money_raw.get("per_add_max")),
        "game_max_total": _count(money_raw.get("game_max_total")),
        "presets": [_count(value) for value in money_raw.get("presets") or []][:6],
    }
    gold = next((row for row in rows if row["alias"] == MONEY_ALIAS), None)
    if gold is None or gold["group"] != "money" or money_raw.get("alias") != MONEY_ALIAS:
        raise ValueError("catalog money row is missing")
    if not 1 <= money["per_add_min"] <= money["per_add_max"] <= money["game_max_total"]:
        raise ValueError("catalog money limits are inconsistent")
    source = document.get("source") or {}
    return PanelCatalog(
        rows=tuple(rows),
        category_order=order,
        toggles=tuple(toggles),
        money=money,
        source_sha256=_text(source.get("sha256"), 64),
    )


def load_catalog(paths: Iterable[Path]) -> PanelCatalog:
    """The first readable, valid catalog; an empty one (with ``error``) if none."""
    errors = []
    for path in paths:
        try:
            if not Path(path).is_file():
                continue
            return parse_catalog(Path(path).read_bytes())
        except (OSError, ValueError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            errors.append(f"{Path(path).name}: {exc}")
    return PanelCatalog(error="; ".join(errors) or "catalog file missing")


def legacy_supported(alias: str) -> bool:
    """Whether a Live Add v3 game mod (v0.3.x/v0.4.0) can add this item."""
    return str(alias or "").lower() in APPROVED_LIVE_ALIASES


def listing(row: Mapping[str, object], toggles: Mapping[str, bool], toggle_names: Mapping[str, str]) -> tuple[bool, str]:
    """(listed, reason) for one row under the current opt-in toggles."""
    group = row.get("group")
    if group == "default":
        return True, ""
    if group == "money":
        return False, "Add Gold on the Money card."
    if group == "excluded":
        return False, str(row.get("reason") or "This item can't be added.")
    key = str(row.get("toggle") or "")
    name = toggle_names.get(key, key)
    if key == "currencies":
        if toggles.get(key):
            return False, "Add it on the Money card."
        return False, f"Turn on {name} on the Money card to add it."
    if toggles.get(key):
        return True, ""
    return False, f"Turn on {name} under More items to add it."


def display_rows(catalog: PanelCatalog, toggles: Mapping[str, bool]) -> list[dict]:
    """Rows for the list model: listed first, then the unlisted search-only rows."""
    names = {toggle.key: toggle.name for toggle in catalog.toggles}
    order = {name: index for index, name in enumerate(catalog.category_order)}
    listed_rows: list[dict] = []
    unlisted_rows: list[dict] = []
    for row in catalog.rows:
        listed, reason = listing(row, toggles, names)
        if is_auto_level_up_item(row["alias"]):
            # Beta Core, Body Core and Omnicard: the game spends them on an
            # upgrade as soon as you have enough, so no switch makes them
            # addable. They are never listed (so the list count leaves them
            # out) and a search row gives that reason, never "Turn on ...".
            listed, reason = False, auto_level_up_reason(row["alias"])
        chip = ""
        if not listed and row["group"] != "money" and not (
            row["toggle"] == "currencies" and toggles.get("currencies")
        ):
            chip = CHIP_NEEDS_DLC if row["dlc"] else CHIP_NOT_AVAILABLE
        entry = dict(row)
        entry.update(
            legacy=legacy_supported(row["alias"]),
            listed=listed,
            listReason=reason,
            chip=chip,
            chipText=CHIP_LABELS.get(chip, ""),
            chipKind=CHIP_KINDS.get(chip, "off"),
            chipReason=reason if not listed else "",
            section="" if listed else "unlisted",
            search=fold_text(f"{row['name']} {row['alias']} {row['category']}"),
        )
        (listed_rows if listed else unlisted_rows).append(entry)
    key = lambda r: (order.get(r["category"], len(order)), r["name"].casefold(), r["alias"])  # noqa: E731
    listed_rows.sort(key=key)
    unlisted_rows.sort(key=key)
    return listed_rows + unlisted_rows
