#pragma once

// sbcore UE4SS shim: the CppUserModBase ABI of the UE4SS.dll that Stellar
// Blade actually loads (RE-UE4SS fork commit d3d10044d12566b869de56164bdaf5dbf36067b8,
// UE4SS.dll SHA-256 F3F0229E8D046824C6D71DB256F1C9BBBDA9652A193643C28FA4E6C329E17670).
//
// That build is based on upstream main after the v3.0.1 tag and has the
// virtual on_ui_init() after on_unreal_init(). The previous shims were copied
// from the v3.0.1 header and had 10 slots, so every slot after slot 2 was off
// by one. Slot order (verified from the DLL's own vftable by
// tools/probe_ue4ss_vtable.py, pinned in ue4ss/runtime_vtable_d3d10044d1.txt):
//
//    0 ~CppUserModBase (scalar deleting destructor)   6 on_lua_start(name, ...)
//    1 on_update                                        7 on_lua_stop(lua, ...)
//    2 on_unreal_init                                   8 on_lua_stop(name, ...)
//    3 on_ui_init                                       9 on_dll_load
//    4 on_program_start                                10 render_tab
//    5 on_lua_start(lua, ...)
//
// (MSVC orders the overloads of one name in reverse declaration order.)
//
// tools/check_vtable_order.py runs on every build and fails it if this
// declaration order, the parameter types or the data members differ from
// third_party/RE-UE4SS/d3d10044d1/CppUserModBase.hpp or from the pinned slot
// table. Do not edit this file without re-running that check.
//
// Data layout (from the DLL's exported constructor): vptr +0x00,
// GUITabs +0x08, ModName +0x20, ModVersion +0x40, ModDescription +0x60,
// ModAuthors +0x80, ModIntendedSDKVersion +0xA0, sizeof 0xC0.
//
// Only the constructor and destructor are imported from UE4SS.dll. The other
// virtuals keep local empty bodies, so a mod's vtable never points into
// UE4SS.dll for a method the mod does not override.

#include <memory>
#include <string>
#include <string_view>
#include <vector>

#define SBCORE_UE4SS_SHIM_RUNTIME "RE-UE4SS d3d10044d1"
#define SBCORE_UE4SS_SHIM_SLOT_COUNT 11

#if defined(SBCORE_SHIM_LOCAL_CTOR)
// Offline layout tests only: defines the constructor/destructor locally so a
// test executable can instantiate the class without UE4SS.dll.
#define SBCORE_SHIM_IMPORT
#else
#define SBCORE_SHIM_IMPORT __declspec(dllimport)
#endif

namespace RC
{
    using StringType = std::wstring;
    using StringViewType = std::wstring_view;

    namespace LuaMadeSimple
    {
        class Lua;
    }

    class CppUserModBase;

    namespace GUI
    {
        class GUITab
        {
          public:
            using RenderFunctionType = void (*)(CppUserModBase*);
        };
    }

    class CppUserModBase
    {
      protected:
        std::vector<std::shared_ptr<GUI::GUITab>> GUITabs{};

      public:
        StringType ModName{};
        StringType ModVersion{};
        StringType ModDescription{};
        StringType ModAuthors{};
        StringType ModIntendedSDKVersion{};

      public:
        SBCORE_SHIM_IMPORT CppUserModBase();
        SBCORE_SHIM_IMPORT virtual ~CppUserModBase();

      public:
        virtual auto on_update() -> void
        {
        }

        // The 'Unreal' module has been initialized.
        virtual auto on_unreal_init() -> void
        {
        }

        // The UI module has been initialized (fork d3d10044d1; absent in v3.0.1).
        virtual auto on_ui_init() -> void
        {
        }

        virtual auto on_program_start() -> void
        {
        }

        virtual auto on_lua_start(StringViewType mod_name,
                                  LuaMadeSimple::Lua& lua,
                                  LuaMadeSimple::Lua& main_lua,
                                  LuaMadeSimple::Lua& async_lua,
                                  std::vector<LuaMadeSimple::Lua*>& hook_luas) -> void
        {
        }

        virtual auto on_lua_start(LuaMadeSimple::Lua& lua,
                                  LuaMadeSimple::Lua& main_lua,
                                  LuaMadeSimple::Lua& async_lua,
                                  std::vector<LuaMadeSimple::Lua*>& hook_luas) -> void
        {
        }

        virtual auto on_lua_stop(StringViewType mod_name,
                                 LuaMadeSimple::Lua& lua,
                                 LuaMadeSimple::Lua& main_lua,
                                 LuaMadeSimple::Lua& async_lua,
                                 std::vector<LuaMadeSimple::Lua*>& hook_luas) -> void
        {
        }

        virtual auto on_lua_stop(LuaMadeSimple::Lua& lua,
                                 LuaMadeSimple::Lua& main_lua,
                                 LuaMadeSimple::Lua& async_lua,
                                 std::vector<LuaMadeSimple::Lua*>& hook_luas) -> void
        {
        }

        virtual auto on_dll_load(StringViewType dll_name) -> void
        {
        }

        virtual auto render_tab() -> void
        {
        }
    };

#if defined(SBCORE_SHIM_LOCAL_CTOR)
    inline CppUserModBase::CppUserModBase() = default;
    inline CppUserModBase::~CppUserModBase() = default;
#endif
} // namespace RC
