# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from pathlib import Path
import PySide6

mod_root = Path(os.environ["SBCHEATGUI_MOD_ROOT"]).resolve()
qt_root = mod_root / "QtPanel"
asset_stage = Path(os.environ["SBCHEATGUI_ASSET_STAGE"]).resolve()
pyside_root = Path(PySide6.__file__).resolve().parent
sys.path.insert(0, str(qt_root))
sys.path.insert(0, str(mod_root / "tools"))
from production_qml import component_package_data
from tools.package_runtime_compat import (
    remove_root_icu_overrides,
    remove_unused_qt_modules,
    replace_root_msvc_runtime,
)

datas = [
    (str(qt_root / "main.qml"), "."),
    (str(qt_root / "pages"), "pages"),
    (str(qt_root / "DesignSystem"), "DesignSystem"),
    (str(qt_root / "UI_REVISION"), "."),
    (str(qt_root / "PRODUCTION_ASSETS.txt"), "."),
    (str(qt_root / "shaders"), "shaders"),
    (str(mod_root / "eve.ico"), "."),
    (str(mod_root / "data" / "item_policy.json"), "data"),
    # Items & Money v0.5 catalog (generated by tools/gen_items_catalog.py).
    (str(mod_root / "data" / "item_catalog_v05.json"), "data"),
    (str(mod_root / "tools" / "PresentMon"), "tools/PresentMon"),
]
datas.extend(component_package_data(qt_root))
# The art the reachable QML names (tools/collect_qt_assets.py). Since 2.5.504
# build 4 that is none: every page is the blurred backdrop, which ships with
# the QML (DesignSystem/brand), so an empty stage adds nothing.
if asset_stage.is_dir() and any(path.is_file() for path in asset_stage.rglob("*")):
    datas.append((str(asset_stage), "assets/brand"))

# Some isolated visual-integration workspaces intentionally omit optional
# launch/helper binaries.  Keep the same spec usable for those workspaces while
# still bundling the files in a complete production tree.
for optional_source, destination in (
    (mod_root / "assets" / "eve-mod-icon-256.png", "assets"),
):
    if optional_source.is_file():
        datas.append((str(optional_source), destination))

excluded_modules = [
    # No video since 2.5.504 build 4 (the Dashboard video layer is gone):
    # Qt Multimedia and its FFmpeg libraries stay out of the exe.
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtWebEngineWidgets",
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DExtras",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.Qt3DRender",
    "PySide6.QtGraphs",
    "PySide6.QtGraphsWidgets",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtQuick3D",
]

a = Analysis(
    [str(qt_root / "main.py")],
    pathex=[str(qt_root)],
    binaries=[],
    datas=datas,
    hiddenimports=[
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtQml",
        "PySide6.QtQuick",
        "PySide6.QtQuickControls2",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excluded_modules,
    noarchive=False,
    optimize=0,
)
                                                                              
                                                                               
                                                                              
a.binaries[:] = remove_root_icu_overrides(a.binaries)

# The QtQml hook bundles every QML module and the Qt DLLs its plugins link.
# Drop the modules the panel never imports (QtWebEngine alone is 195 MB and
# could not run without QtWebEngineProcess.exe); see package_runtime_compat.
a.binaries[:] = remove_unused_qt_modules(a.binaries)
a.datas[:] = remove_unused_qt_modules(a.datas)

# A frozen process can load a scoped shiboken/Python MSVC DLL before QtCore.
# Those wheel-local copies are not interchangeable despite similar versions,
# and QtCore then fails with ERROR_PROC_NOT_FOUND. Pin one complete, matching
# PySide6 runtime family at the executable root so Windows resolves it first.
a.binaries[:] = replace_root_msvc_runtime(
    a.binaries,
    {
        "concrt140.dll": pyside_root / "concrt140.dll",
        "msvcp140.dll": pyside_root / "msvcp140.dll",
        "msvcp140_1.dll": pyside_root / "msvcp140_1.dll",
        "msvcp140_2.dll": pyside_root / "msvcp140_2.dll",
        "msvcp140_codecvt_ids.dll": pyside_root / "msvcp140_codecvt_ids.dll",
        "VCRUNTIME140.dll": pyside_root / "VCRUNTIME140.dll",
        "VCRUNTIME140_1.dll": pyside_root / "VCRUNTIME140_1.dll",
    },
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="Stellar Blade Mod Suite",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[str(mod_root / "eve.ico")],
)
