-- Stellar Blade Mod Suite - fail-closed Live Add v4 bridge.
--
-- This bridge has one responsibility: translate a release-approved item alias
-- into the FName index consumed by a dedicated SBLiveAddNative module (0.5.0,
-- protocol native-live-add-v4). It has no hooks, key binds, UObject scans,
-- save editing, pickup/drop, equipment, progression, health, location, or
-- teleport route. It never clamps a quantity: an amount outside the item's
-- range is refused, and the native repeats every check (and more) itself.

local UEHelpers = require("UEHelpers")

local thisDir = debug.getinfo(1, "S").source:match("@?(.*[\\/])") or ""
local panelRoot = thisDir .. "../../SBCheatGUI/"
local STATE_FILE = panelRoot .. "gui_state.txt"
local HEARTBEAT_FILE = panelRoot .. "sbcheat_heartbeat.txt"
local STATUS_FILE = panelRoot .. "item_spawn_status.txt"
local NATIVE_HEARTBEAT_FILE = panelRoot .. "live_add_native_heartbeat.txt"
local NATIVE_REQUEST_FILE = panelRoot .. "live_add_native_request.txt"
local NATIVE_RESULT_FILE = panelRoot .. "live_add_native_result.txt"
local NATIVE_MODULE = "SBLiveAddNative"

local SPAWN_API = "native-live-add-v4"
local BRIDGE_ID = "trusted-live-add-only"
local NATIVE_STALE_TICKS = 8
local PANEL_REQUEST_MAX_AGE_SECONDS = 2

-- Generated from the v0.5 catalog's decisions (addable rows only). Runtime
-- catalogs are display data only and can never extend this embedded authority.
-- @@GENERATED_ALLOWLIST_BEGIN@@
-- Generated by tools/gen_item_allowlist.py from the v0.5 catalog
-- (SHA-256 605000FB096A87A8EF0CC7B805CB001492F6052FA1C66C4C880AE5E0394205E6); do not edit. Lower-case key ->
-- { exact alias, largest quantity one add may request }. SBLiveAddNative
-- repeats every check (and more) at its own boundary.
local APPROVED_ALIASES = {
    ["2dquantumwafer"] = { "2DQuantumWafer", 99 },
    ["adamcostume_001"] = { "AdamCostume_001", 1 },
    ["adamcostume_003"] = { "AdamCostume_003", 1 },
    ["adamcostume_003_var2"] = { "AdamCostume_003_Var2", 1 },
    ["adamcostume_004"] = { "AdamCostume_004", 1 },
    ["adamcostume_004_var2"] = { "AdamCostume_004_Var2", 1 },
    ["adamcostume_christmas_01"] = { "AdamCostume_Christmas_01", 1 },
    ["bs_01"] = { "BS_01", 1 },
    ["bs_01_var3"] = { "BS_01_Var3", 1 },
    ["bs_02"] = { "BS_02", 1 },
    ["bs_02_var2"] = { "BS_02_Var2", 1 },
    ["bs_03"] = { "BS_03", 1 },
    ["bs_03_var2"] = { "BS_03_Var2", 1 },
    ["bs_04"] = { "BS_04", 1 },
    ["bs_04_var2"] = { "BS_04_Var2", 1 },
    ["bs_05_e"] = { "BS_05_E", 1 },
    ["bs_05_var2_e"] = { "BS_05_Var2_E", 1 },
    ["bs_07"] = { "BS_07", 1 },
    ["bs_07_var2"] = { "BS_07_Var2", 1 },
    ["bs_08"] = { "BS_08", 1 },
    ["bs_08_var2"] = { "BS_08_Var2", 1 },
    ["bs_09_2"] = { "BS_09_2", 1 },
    ["bs_09_2_var2"] = { "BS_09_2_Var2", 1 },
    ["bs_10"] = { "BS_10", 1 },
    ["bs_102"] = { "BS_102", 1 },
    ["bs_11"] = { "BS_11", 1 },
    ["bs_13"] = { "BS_13", 1 },
    ["bs_13_var2"] = { "BS_13_Var2", 1 },
    ["bs_14_e"] = { "BS_14_E", 1 },
    ["bs_14_var2_e"] = { "BS_14_Var2_E", 1 },
    ["bs_15"] = { "BS_15", 1 },
    ["bs_15_var2_e"] = { "BS_15_Var2_E", 1 },
    ["bs_16"] = { "BS_16", 1 },
    ["bs_16_var2"] = { "BS_16_Var2", 1 },
    ["bs_17"] = { "BS_17", 1 },
    ["bs_18"] = { "BS_18", 1 },
    ["bs_19"] = { "BS_19", 1 },
    ["bs_19_var2"] = { "BS_19_Var2", 1 },
    ["bs_20"] = { "BS_20", 1 },
    ["bs_20_var2"] = { "BS_20_Var2", 1 },
    ["bs_21"] = { "BS_21", 1 },
    ["bs_21_var2"] = { "BS_21_Var2", 1 },
    ["bs_22"] = { "BS_22", 1 },
    ["bs_22_var2_e"] = { "BS_22_Var2_E", 1 },
    ["bs_23"] = { "BS_23", 1 },
    ["bs_23_var2"] = { "BS_23_Var2", 1 },
    ["bs_24_e"] = { "BS_24_E", 1 },
    ["bs_24_var2"] = { "BS_24_Var2", 1 },
    ["bs_26"] = { "BS_26", 1 },
    ["bs_26_var2"] = { "BS_26_Var2", 1 },
    ["bs_30"] = { "BS_30", 1 },
    ["bs_30_var2"] = { "BS_30_Var2", 1 },
    ["bs_31"] = { "BS_31", 1 },
    ["bs_31_var2"] = { "BS_31_Var2", 1 },
    ["bs_32"] = { "BS_32", 1 },
    ["bs_33"] = { "BS_33", 1 },
    ["bs_33_var2"] = { "BS_33_Var2", 1 },
    ["bs_34"] = { "BS_34", 1 },
    ["bs_34_var2"] = { "BS_34_Var2", 1 },
    ["bs_37"] = { "BS_37", 1 },
    ["bs_37_var2"] = { "BS_37_Var2", 1 },
    ["bs_37_var3"] = { "BS_37_Var3", 1 },
    ["bs_38"] = { "BS_38", 1 },
    ["bs_38_var2"] = { "BS_38_Var2", 1 },
    ["bs_40"] = { "BS_40", 1 },
    ["bs_40_var2"] = { "BS_40_Var2", 1 },
    ["bs_40_var3"] = { "BS_40_Var3", 1 },
    ["bs_41"] = { "BS_41", 1 },
    ["bs_41_var2"] = { "BS_41_Var2", 1 },
    ["bs_42"] = { "BS_42", 1 },
    ["bs_42_var2"] = { "BS_42_Var2", 1 },
    ["bs_43"] = { "BS_43", 1 },
    ["bs_43_var2"] = { "BS_43_Var2", 1 },
    ["bs_44"] = { "BS_44", 1 },
    ["bs_44_var2"] = { "BS_44_Var2", 1 },
    ["bs_44_var3_e"] = { "BS_44_Var3_E", 1 },
    ["bs_45"] = { "BS_45", 1 },
    ["bs_45_var2"] = { "BS_45_Var2", 1 },
    ["bs_47"] = { "BS_47", 1 },
    ["bs_47_var2"] = { "BS_47_Var2", 1 },
    ["bs_48"] = { "BS_48", 1 },
    ["bs_48_var2"] = { "BS_48_Var2", 1 },
    ["bs_50"] = { "BS_50", 1 },
    ["bs_50_var2"] = { "BS_50_Var2", 1 },
    ["bs_52"] = { "BS_52", 1 },
    ["bs_53"] = { "BS_53", 1 },
    ["bs_53_var2"] = { "BS_53_Var2", 1 },
    ["bs_54"] = { "BS_54", 1 },
    ["bs_55"] = { "BS_55", 1 },
    ["bs_55_var2"] = { "BS_55_Var2", 1 },
    ["bs_56"] = { "BS_56", 1 },
    ["bs_57"] = { "BS_57", 1 },
    ["bs_58"] = { "BS_58", 1 },
    ["bs_60"] = { "BS_60", 1 },
    ["bs_bear"] = { "BS_Bear", 1 },
    ["bs_bear_var2"] = { "BS_Bear_Var2", 1 },
    ["bs_black_leather_bikini"] = { "BS_Black_Leather_bikini", 1 },
    ["bs_black_leather_bikini_var2"] = { "BS_Black_Leather_bikini_Var2", 1 },
    ["bs_blue_suit_e"] = { "BS_Blue_Suit_E", 1 },
    ["bs_christmas_01"] = { "BS_Christmas_01", 1 },
    ["bs_default"] = { "BS_Default", 1 },
    ["bs_eve_04"] = { "BS_EVE_04", 1 },
    ["bs_eve_04_var2"] = { "BS_EVE_04_Var2", 1 },
    ["bs_green_suit"] = { "BS_Green_Suit", 1 },
    ["bs_leather_jean"] = { "BS_Leather_Jean", 1 },
    ["bs_leather_jean_var2"] = { "BS_Leather_Jean_Var2", 1 },
    ["bs_onemillion_01"] = { "BS_OneMillion_01", 1 },
    ["bs_raven"] = { "BS_Raven", 1 },
    ["bs_royalguard_01"] = { "BS_RoyalGuard_01", 1 },
    ["bs_sailor_jean"] = { "BS_Sailor_Jean", 1 },
    ["bs_sailor_jean_var2"] = { "BS_Sailor_Jean_Var2", 1 },
    ["bs_silverkunoichi"] = { "BS_SilverKunoichi", 1 },
    ["bs_silverkunoichi_var2"] = { "BS_SilverKunoichi_Var2", 1 },
    ["bs_white_jean"] = { "BS_White_Jean", 1 },
    ["bs_white_jean_var2"] = { "BS_White_Jean_Var2", 1 },
    ["bs_yellow_suit"] = { "BS_Yellow_Suit", 1 },
    ["bs_yellow_suit_jacket"] = { "BS_Yellow_Suit_Jacket", 1 },
    ["bs_yellow_suit_jacket_var2"] = { "BS_Yellow_Suit_Jacket_Var2", 1 },
    ["bs_yellow_suit_var2"] = { "BS_Yellow_Suit_Var2", 1 },
    ["betacore"] = { "BetaCore", 99 },
    ["betacrystal"] = { "BetaCrystal", 1000000 },
    ["bodycore"] = { "BodyCore", 99 },
    ["bullet_explosive"] = { "Bullet_Explosive", 99 },
    ["bullet_missile"] = { "Bullet_Missile", 99 },
    ["bullet_nikke"] = { "Bullet_Nikke", 99 },
    ["bullet_normal"] = { "Bullet_Normal", 99 },
    ["bullet_railgun"] = { "Bullet_Railgun", 99 },
    ["bullet_scatter"] = { "Bullet_Scatter", 99 },
    ["can_001"] = { "Can_001", 1 },
    ["can_002"] = { "Can_002", 1 },
    ["can_003"] = { "Can_003", 1 },
    ["can_004"] = { "Can_004", 1 },
    ["can_005"] = { "Can_005", 1 },
    ["can_006"] = { "Can_006", 1 },
    ["can_007"] = { "Can_007", 1 },
    ["can_008"] = { "Can_008", 1 },
    ["can_009"] = { "Can_009", 1 },
    ["can_010"] = { "Can_010", 1 },
    ["can_011"] = { "Can_011", 1 },
    ["can_012"] = { "Can_012", 1 },
    ["can_013"] = { "Can_013", 1 },
    ["can_014"] = { "Can_014", 1 },
    ["can_015"] = { "Can_015", 1 },
    ["can_016"] = { "Can_016", 1 },
    ["can_017"] = { "Can_017", 1 },
    ["can_018"] = { "Can_018", 1 },
    ["can_019"] = { "Can_019", 1 },
    ["can_020"] = { "Can_020", 1 },
    ["can_021"] = { "Can_021", 1 },
    ["can_022"] = { "Can_022", 1 },
    ["can_023"] = { "Can_023", 1 },
    ["can_024"] = { "Can_024", 1 },
    ["can_025"] = { "Can_025", 1 },
    ["can_026"] = { "Can_026", 1 },
    ["can_027"] = { "Can_027", 1 },
    ["can_028"] = { "Can_028", 1 },
    ["can_029"] = { "Can_029", 1 },
    ["can_030"] = { "Can_030", 1 },
    ["can_031"] = { "Can_031", 1 },
    ["can_032"] = { "Can_032", 1 },
    ["can_033"] = { "Can_033", 1 },
    ["can_034"] = { "Can_034", 1 },
    ["can_035"] = { "Can_035", 1 },
    ["can_036"] = { "Can_036", 1 },
    ["can_037"] = { "Can_037", 1 },
    ["can_038"] = { "Can_038", 1 },
    ["can_039"] = { "Can_039", 1 },
    ["can_040"] = { "Can_040", 1 },
    ["can_041"] = { "Can_041", 1 },
    ["can_042"] = { "Can_042", 1 },
    ["can_043"] = { "Can_043", 1 },
    ["can_044"] = { "Can_044", 1 },
    ["can_045"] = { "Can_045", 1 },
    ["can_046"] = { "Can_046", 1 },
    ["can_047"] = { "Can_047", 1 },
    ["can_048"] = { "Can_048", 1 },
    ["can_049"] = { "Can_049", 1 },
    ["concussiongrenade"] = { "ConcussionGrenade", 99 },
    ["designpattern_bs_01"] = { "DesignPattern_BS_01", 1 },
    ["designpattern_bs_01_var2"] = { "DesignPattern_BS_01_Var2", 1 },
    ["designpattern_bs_01_var3"] = { "DesignPattern_BS_01_Var3", 1 },
    ["designpattern_bs_02"] = { "DesignPattern_BS_02", 1 },
    ["designpattern_bs_02_var2"] = { "DesignPattern_BS_02_Var2", 1 },
    ["designpattern_bs_03"] = { "DesignPattern_BS_03", 1 },
    ["designpattern_bs_03_var2"] = { "DesignPattern_BS_03_Var2", 1 },
    ["designpattern_bs_04"] = { "DesignPattern_BS_04", 1 },
    ["designpattern_bs_04_var2"] = { "DesignPattern_BS_04_Var2", 1 },
    ["designpattern_bs_05"] = { "DesignPattern_BS_05", 1 },
    ["designpattern_bs_05_var2"] = { "DesignPattern_BS_05_Var2", 1 },
    ["designpattern_bs_07"] = { "DesignPattern_BS_07", 1 },
    ["designpattern_bs_07_var2"] = { "DesignPattern_BS_07_Var2", 1 },
    ["designpattern_bs_08"] = { "DesignPattern_BS_08", 1 },
    ["designpattern_bs_08_var2"] = { "DesignPattern_BS_08_Var2", 1 },
    ["designpattern_bs_09_2"] = { "DesignPattern_BS_09_2", 1 },
    ["designpattern_bs_09_2_var2"] = { "DesignPattern_BS_09_2_Var2", 1 },
    ["designpattern_bs_10"] = { "DesignPattern_BS_10", 1 },
    ["designpattern_bs_102"] = { "DesignPattern_BS_102", 1 },
    ["designpattern_bs_11"] = { "DesignPattern_BS_11", 1 },
    ["designpattern_bs_13"] = { "DesignPattern_BS_13", 1 },
    ["designpattern_bs_13_var2"] = { "DesignPattern_BS_13_Var2", 1 },
    ["designpattern_bs_14"] = { "DesignPattern_BS_14", 1 },
    ["designpattern_bs_14_var2"] = { "DesignPattern_BS_14_Var2", 1 },
    ["designpattern_bs_15"] = { "DesignPattern_BS_15", 1 },
    ["designpattern_bs_15_var2"] = { "DesignPattern_BS_15_Var2", 1 },
    ["designpattern_bs_16"] = { "DesignPattern_BS_16", 1 },
    ["designpattern_bs_16_var2"] = { "DesignPattern_BS_16_Var2", 1 },
    ["designpattern_bs_17"] = { "DesignPattern_BS_17", 1 },
    ["designpattern_bs_19"] = { "DesignPattern_BS_19", 1 },
    ["designpattern_bs_19_var2"] = { "DesignPattern_BS_19_Var2", 1 },
    ["designpattern_bs_20"] = { "DesignPattern_BS_20", 1 },
    ["designpattern_bs_20_var2"] = { "DesignPattern_BS_20_Var2", 1 },
    ["designpattern_bs_21"] = { "DesignPattern_BS_21", 1 },
    ["designpattern_bs_21_var2"] = { "DesignPattern_BS_21_Var2", 1 },
    ["designpattern_bs_22"] = { "DesignPattern_BS_22", 1 },
    ["designpattern_bs_22_var2"] = { "DesignPattern_BS_22_Var2", 1 },
    ["designpattern_bs_23"] = { "DesignPattern_BS_23", 1 },
    ["designpattern_bs_23_var2"] = { "DesignPattern_BS_23_Var2", 1 },
    ["designpattern_bs_24"] = { "DesignPattern_BS_24", 1 },
    ["designpattern_bs_24_var2"] = { "DesignPattern_BS_24_Var2", 1 },
    ["designpattern_bs_26"] = { "DesignPattern_BS_26", 1 },
    ["designpattern_bs_26_var2"] = { "DesignPattern_BS_26_Var2", 1 },
    ["designpattern_bs_30"] = { "DesignPattern_BS_30", 1 },
    ["designpattern_bs_30_var2"] = { "DesignPattern_BS_30_Var2", 1 },
    ["designpattern_bs_31"] = { "DesignPattern_BS_31", 1 },
    ["designpattern_bs_31_var2"] = { "DesignPattern_BS_31_Var2", 1 },
    ["designpattern_bs_32"] = { "DesignPattern_BS_32", 1 },
    ["designpattern_bs_33"] = { "DesignPattern_BS_33", 1 },
    ["designpattern_bs_34"] = { "DesignPattern_BS_34", 1 },
    ["designpattern_bs_34_var2"] = { "DesignPattern_BS_34_Var2", 1 },
    ["designpattern_bs_37"] = { "DesignPattern_BS_37", 1 },
    ["designpattern_bs_37_var2"] = { "DesignPattern_BS_37_Var2", 1 },
    ["designpattern_bs_37_var3"] = { "DesignPattern_BS_37_Var3", 1 },
    ["designpattern_bs_38"] = { "DesignPattern_BS_38", 1 },
    ["designpattern_bs_38_var2"] = { "DesignPattern_BS_38_Var2", 1 },
    ["designpattern_bs_40"] = { "DesignPattern_BS_40", 1 },
    ["designpattern_bs_40_var2"] = { "DesignPattern_BS_40_Var2", 1 },
    ["designpattern_bs_40_var3"] = { "DesignPattern_BS_40_Var3", 1 },
    ["designpattern_bs_41"] = { "DesignPattern_BS_41", 1 },
    ["designpattern_bs_41_var2"] = { "DesignPattern_BS_41_Var2", 1 },
    ["designpattern_bs_42"] = { "DesignPattern_BS_42", 1 },
    ["designpattern_bs_42_var2"] = { "DesignPattern_BS_42_Var2", 1 },
    ["designpattern_bs_43"] = { "DesignPattern_BS_43", 1 },
    ["designpattern_bs_43_var2"] = { "DesignPattern_BS_43_Var2", 1 },
    ["designpattern_bs_44"] = { "DesignPattern_BS_44", 1 },
    ["designpattern_bs_44_var2"] = { "DesignPattern_BS_44_Var2", 1 },
    ["designpattern_bs_44_var3"] = { "DesignPattern_BS_44_Var3", 1 },
    ["designpattern_bs_45"] = { "DesignPattern_BS_45", 1 },
    ["designpattern_bs_45_var2"] = { "DesignPattern_BS_45_Var2", 1 },
    ["designpattern_bs_47"] = { "DesignPattern_BS_47", 1 },
    ["designpattern_bs_47_var2"] = { "DesignPattern_BS_47_Var2", 1 },
    ["designpattern_bs_48"] = { "DesignPattern_BS_48", 1 },
    ["designpattern_bs_48_var2"] = { "DesignPattern_BS_48_Var2", 1 },
    ["designpattern_bs_50"] = { "DesignPattern_BS_50", 1 },
    ["designpattern_bs_50_var2"] = { "DesignPattern_BS_50_Var2", 1 },
    ["designpattern_bs_53"] = { "DesignPattern_BS_53", 1 },
    ["designpattern_bs_53_var2"] = { "DesignPattern_BS_53_Var2", 1 },
    ["designpattern_bs_54"] = { "DesignPattern_BS_54", 1 },
    ["designpattern_bs_55"] = { "DesignPattern_BS_55", 1 },
    ["designpattern_bs_55_var2"] = { "DesignPattern_BS_55_Var2", 1 },
    ["designpattern_bs_56"] = { "DesignPattern_BS_56", 1 },
    ["designpattern_bs_57"] = { "DesignPattern_BS_57", 1 },
    ["designpattern_bs_58"] = { "DesignPattern_BS_58", 1 },
    ["designpattern_bs_60"] = { "DesignPattern_BS_60", 1 },
    ["designpattern_bs_99"] = { "DesignPattern_BS_99", 1 },
    ["designpattern_bs_bear"] = { "DesignPattern_BS_Bear", 1 },
    ["designpattern_bs_bear_var2"] = { "DesignPattern_BS_Bear_Var2", 1 },
    ["designpattern_bs_black_leather_bikini"] = { "DesignPattern_BS_Black_Leather_bikini", 1 },
    ["designpattern_bs_black_leather_bikini_var2"] = { "DesignPattern_BS_Black_Leather_bikini_Var2", 1 },
    ["designpattern_bs_blue_suit"] = { "DesignPattern_BS_Blue_Suit", 1 },
    ["designpattern_bs_default"] = { "DesignPattern_BS_Default", 1 },
    ["designpattern_bs_default_var2"] = { "DesignPattern_BS_Default_Var2", 1 },
    ["designpattern_bs_default_var3"] = { "DesignPattern_BS_Default_Var3", 1 },
    ["designpattern_bs_eve_04"] = { "DesignPattern_BS_EVE_04", 1 },
    ["designpattern_bs_eve_04_var2"] = { "DesignPattern_BS_EVE_04_Var2", 1 },
    ["designpattern_bs_leather_jean"] = { "DesignPattern_BS_Leather_Jean", 1 },
    ["designpattern_bs_leather_jean_var2"] = { "DesignPattern_BS_Leather_Jean_Var2", 1 },
    ["designpattern_bs_raven"] = { "DesignPattern_BS_Raven", 1 },
    ["designpattern_bs_sailor_jean"] = { "DesignPattern_BS_Sailor_Jean", 1 },
    ["designpattern_bs_sailor_jean_var2"] = { "DesignPattern_BS_Sailor_Jean_Var2", 1 },
    ["designpattern_bs_silverkunoichi"] = { "DesignPattern_BS_SilverKunoichi", 1 },
    ["designpattern_bs_silverkunoichi_var2"] = { "DesignPattern_BS_SilverKunoichi_Var2", 1 },
    ["designpattern_bs_white_jean"] = { "DesignPattern_BS_White_Jean", 1 },
    ["designpattern_bs_white_jean_var2"] = { "DesignPattern_BS_White_Jean_Var2", 1 },
    ["designpattern_bs_yellow_suit"] = { "DesignPattern_BS_Yellow_Suit", 1 },
    ["designpattern_bs_yellow_suit_jacket"] = { "DesignPattern_BS_Yellow_Suit_Jacket", 1 },
    ["designpattern_bs_yellow_suit_jacket_var2"] = { "DesignPattern_BS_Yellow_Suit_Jacket_Var2", 1 },
    ["designpattern_bs_yellow_suit_var2"] = { "DesignPattern_BS_Yellow_Suit_Var2", 1 },
    ["dronecore"] = { "DroneCore", 99 },
    ["droneseal_001"] = { "DroneSeal_001", 1 },
    ["droneseal_002"] = { "DroneSeal_002", 1 },
    ["droneseal_002_var2"] = { "DroneSeal_002_Var2", 1 },
    ["droneseal_004"] = { "DroneSeal_004", 1 },
    ["droneseal_004_var2"] = { "DroneSeal_004_Var2", 1 },
    ["droneseal_christmas_01"] = { "DroneSeal_Christmas_01", 1 },
    ["ecelluloserayon"] = { "ECelluloseRayon", 99 },
    ["etc_item_vendingmachinecoin"] = { "ETC_Item_VendingMachineCoin", 9999 },
    ["earring_001"] = { "Earring_001", 1 },
    ["earring_001_var2"] = { "Earring_001_Var2", 1 },
    ["earring_002"] = { "Earring_002", 1 },
    ["earring_002_var2"] = { "Earring_002_Var2", 1 },
    ["earring_003"] = { "Earring_003", 1 },
    ["earring_003_var2"] = { "Earring_003_Var2", 1 },
    ["earring_004"] = { "Earring_004", 1 },
    ["earring_006"] = { "Earring_006", 1 },
    ["earring_007"] = { "Earring_007", 1 },
    ["earring_008"] = { "Earring_008", 1 },
    ["earring_008_var2"] = { "Earring_008_Var2", 1 },
    ["earring_009"] = { "Earring_009", 1 },
    ["earring_010"] = { "Earring_010", 1 },
    ["earring_012"] = { "Earring_012", 1 },
    ["earring_013"] = { "Earring_013", 1 },
    ["earring_014"] = { "Earring_014", 1 },
    ["earring_015"] = { "Earring_015", 1 },
    ["earring_016"] = { "Earring_016", 1 },
    ["earring_017"] = { "Earring_017", 1 },
    ["earring_018"] = { "Earring_018", 1 },
    ["earring_christmas_01"] = { "Earring_Christmas_01", 1 },
    ["earring_christmas_02"] = { "Earring_Christmas_02", 1 },
    ["elastomerfiber"] = { "ElastomerFiber", 99 },
    ["faceaccessory_001"] = { "FaceAccessory_001", 1 },
    ["faceaccessory_002"] = { "FaceAccessory_002", 1 },
    ["faceaccessory_002_var2"] = { "FaceAccessory_002_Var2", 1 },
    ["faceaccessory_004"] = { "FaceAccessory_004", 1 },
    ["faceaccessory_005"] = { "FaceAccessory_005", 1 },
    ["faceaccessory_006"] = { "FaceAccessory_006", 1 },
    ["faceaccessory_007"] = { "FaceAccessory_007", 1 },
    ["faceaccessory_008"] = { "FaceAccessory_008", 1 },
    ["faceaccessory_009"] = { "FaceAccessory_009", 1 },
    ["faceaccessory_010"] = { "FaceAccessory_010", 1 },
    ["faceaccessory_011"] = { "FaceAccessory_011", 1 },
    ["faceaccessory_013"] = { "FaceAccessory_013", 1 },
    ["faceaccessory_026"] = { "FaceAccessory_026", 1 },
    ["faceaccessory_027"] = { "FaceAccessory_027", 1 },
    ["faceaccessory_028"] = { "FaceAccessory_028", 1 },
    ["faceaccessory_029"] = { "FaceAccessory_029", 1 },
    ["faceaccessory_christmas_01"] = { "FaceAccessory_Christmas_01", 1 },
    ["fish_arowana"] = { "Fish_Arowana", 99 },
    ["fish_betta"] = { "Fish_Betta", 99 },
    ["fish_box1"] = { "Fish_Box1", 99 },
    ["fish_box2"] = { "Fish_Box2", 99 },
    ["fish_box3"] = { "Fish_Box3", 99 },
    ["fish_box4"] = { "Fish_Box4", 99 },
    ["fish_butterflyfish"] = { "Fish_ButterflyFish", 99 },
    ["fish_cannedfish"] = { "Fish_CannedFish", 99 },
    ["fish_cannerham"] = { "Fish_CannerHam", 99 },
    ["fish_channelcatfish"] = { "Fish_ChannelCatfish", 99 },
    ["fish_dunkleosteus"] = { "Fish_Dunkleosteus", 99 },
    ["fish_fancycarp"] = { "Fish_FancyCarp", 99 },
    ["fish_fishcake"] = { "Fish_FishCake", 99 },
    ["fish_flyingfish"] = { "Fish_FlyingFish", 99 },
    ["fish_footballfish"] = { "Fish_FootBallfish", 99 },
    ["fish_goby"] = { "Fish_Goby", 99 },
    ["fish_goldfish"] = { "Fish_GoldFish", 99 },
    ["fish_greatwhiteshark"] = { "Fish_GreatWhiteShark", 99 },
    ["fish_halibut"] = { "Fish_Halibut", 99 },
    ["fish_lobster"] = { "Fish_Lobster", 99 },
    ["fish_mahimahi"] = { "Fish_Mahimahi", 99 },
    ["fish_molamola"] = { "Fish_MolaMola", 99 },
    ["fish_nuclearwaste"] = { "Fish_NuclearWaste", 99 },
    ["fish_pirarucu"] = { "Fish_Pirarucu", 99 },
    ["fish_porcupinefish"] = { "Fish_PorcupineFish", 99 },
    ["fish_sailfish"] = { "Fish_SailFish", 99 },
    ["fish_salmon"] = { "Fish_Salmon", 99 },
    ["fish_seabass"] = { "Fish_SeaBass", 99 },
    ["fish_seabream"] = { "Fish_SeaBream", 99 },
    ["fish_tire"] = { "Fish_Tire", 99 },
    ["fish_triggerfish"] = { "Fish_Triggerfish", 99 },
    ["fish_tuna"] = { "Fish_Tuna", 99 },
    ["fish_whaleshark"] = { "Fish_WhaleShark", 99 },
    ["fish_mackerel"] = { "Fish_mackerel", 99 },
    ["fishingpoint"] = { "FishingPoint", 9999 },
    ["fishingskillbook1"] = { "FishingSkillBook1", 1 },
    ["fishingskillbook2"] = { "FishingSkillBook2", 1 },
    ["fishingskillbook3"] = { "FishingSkillBook3", 1 },
    ["fishingskillbook4"] = { "FishingSkillBook4", 1 },
    ["flashgrenade"] = { "FlashGrenade", 99 },
    ["gearcore"] = { "GearCore", 99 },
    ["gear_additivebetaskilldamage_common"] = { "Gear_AdditiveBetaSkillDamage_Common", 1 },
    ["gear_additivebetaskilldamage_common_mk2"] = { "Gear_AdditiveBetaSkillDamage_Common_MK2", 1 },
    ["gear_additivebetaskilldamage_rare"] = { "Gear_AdditiveBetaSkillDamage_Rare", 1 },
    ["gear_additivebetaskilldamage_rare_mk2"] = { "Gear_AdditiveBetaSkillDamage_Rare_MK2", 1 },
    ["gear_additivebetaskilldamage_uncommon"] = { "Gear_AdditiveBetaSkillDamage_Uncommon", 1 },
    ["gear_additivebetaskilldamage_uncommon_mk2"] = { "Gear_AdditiveBetaSkillDamage_Uncommon_MK2", 1 },
    ["gear_additivebustskilldamage_common"] = { "Gear_AdditiveBustSkillDamage_Common", 1 },
    ["gear_additivebustskilldamage_common_mk2"] = { "Gear_AdditiveBustSkillDamage_Common_MK2", 1 },
    ["gear_additivebustskilldamage_rare"] = { "Gear_AdditiveBustSkillDamage_Rare", 1 },
    ["gear_additivebustskilldamage_rare_mk2"] = { "Gear_AdditiveBustSkillDamage_Rare_MK2", 1 },
    ["gear_additivebustskilldamage_uncommon"] = { "Gear_AdditiveBustSkillDamage_Uncommon", 1 },
    ["gear_additivebustskilldamage_uncommon_mk2"] = { "Gear_AdditiveBustSkillDamage_Uncommon_MK2", 1 },
    ["gear_additivefixeddamage_common"] = { "Gear_AdditiveFixedDamage_Common", 1 },
    ["gear_additivefixeddamage_common_mk2"] = { "Gear_AdditiveFixedDamage_Common_MK2", 1 },
    ["gear_additivefixeddamage_rare"] = { "Gear_AdditiveFixedDamage_Rare", 1 },
    ["gear_additivefixeddamage_rare_mk2"] = { "Gear_AdditiveFixedDamage_Rare_MK2", 1 },
    ["gear_additivefixeddamage_uncommon"] = { "Gear_AdditiveFixedDamage_Uncommon", 1 },
    ["gear_additivefixeddamage_uncommon_mk2"] = { "Gear_AdditiveFixedDamage_Uncommon_MK2", 1 },
    ["gear_additivegiveandrecivedamagerate_common"] = { "Gear_AdditiveGiveAndReciveDamageRate_Common", 1 },
    ["gear_additivegiveandrecivedamagerate_common_mk2"] = { "Gear_AdditiveGiveAndReciveDamageRate_Common_MK2", 1 },
    ["gear_additivegiveandrecivedamagerate_rare"] = { "Gear_AdditiveGiveAndReciveDamageRate_Rare", 1 },
    ["gear_additivegiveandrecivedamagerate_rare_mk2"] = { "Gear_AdditiveGiveAndReciveDamageRate_Rare_MK2", 1 },
    ["gear_additivegiveandrecivedamagerate_uncommon"] = { "Gear_AdditiveGiveAndReciveDamageRate_Uncommon", 1 },
    ["gear_additivegiveandrecivedamagerate_uncommon_mk2"] = { "Gear_AdditiveGiveAndReciveDamageRate_Uncommon_MK2", 1 },
    ["gear_attackspeed_common"] = { "Gear_AttackSpeed_Common", 1 },
    ["gear_attackspeed_common_mk2"] = { "Gear_AttackSpeed_Common_MK2", 1 },
    ["gear_attackspeed_rare"] = { "Gear_AttackSpeed_Rare", 1 },
    ["gear_attackspeed_rare_mk2"] = { "Gear_AttackSpeed_Rare_MK2", 1 },
    ["gear_attackspeed_uncommon"] = { "Gear_AttackSpeed_Uncommon", 1 },
    ["gear_attackspeed_uncommon_mk2"] = { "Gear_AttackSpeed_Uncommon_MK2", 1 },
    ["gear_betacrystaladditiverate_common"] = { "Gear_BetaCrystalAdditiveRate_Common", 1 },
    ["gear_betacrystaladditiverate_common_mk2"] = { "Gear_BetaCrystalAdditiveRate_Common_MK2", 1 },
    ["gear_betacrystaladditiverate_rare"] = { "Gear_BetaCrystalAdditiveRate_Rare", 1 },
    ["gear_betacrystaladditiverate_rare_mk2"] = { "Gear_BetaCrystalAdditiveRate_Rare_MK2", 1 },
    ["gear_betacrystaladditiverate_uncommon"] = { "Gear_BetaCrystalAdditiveRate_Uncommon", 1 },
    ["gear_betacrystaladditiverate_uncommon_mk2"] = { "Gear_BetaCrystalAdditiveRate_Uncommon_MK2", 1 },
    ["gear_betagaugeadditiverate_common"] = { "Gear_BetaGaugeAdditiveRate_Common", 1 },
    ["gear_betagaugeadditiverate_common_mk2"] = { "Gear_BetaGaugeAdditiveRate_Common_MK2", 1 },
    ["gear_betagaugeadditiverate_rare"] = { "Gear_BetaGaugeAdditiveRate_Rare", 1 },
    ["gear_betagaugeadditiverate_rare_mk2"] = { "Gear_BetaGaugeAdditiveRate_Rare_MK2", 1 },
    ["gear_betagaugeadditiverate_uncommon"] = { "Gear_BetaGaugeAdditiveRate_Uncommon", 1 },
    ["gear_betagaugeadditiverate_uncommon_mk2"] = { "Gear_BetaGaugeAdditiveRate_Uncommon_MK2", 1 },
    ["gear_burstgaugeadditiverate_common"] = { "Gear_BurstGaugeAdditiveRate_Common", 1 },
    ["gear_burstgaugeadditiverate_common_mk2"] = { "Gear_BurstGaugeAdditiveRate_Common_MK2", 1 },
    ["gear_burstgaugeadditiverate_rare"] = { "Gear_BurstGaugeAdditiveRate_Rare", 1 },
    ["gear_burstgaugeadditiverate_rare_mk2"] = { "Gear_BurstGaugeAdditiveRate_Rare_MK2", 1 },
    ["gear_burstgaugeadditiverate_uncommon"] = { "Gear_BurstGaugeAdditiveRate_Uncommon", 1 },
    ["gear_burstgaugeadditiverate_uncommon_mk2"] = { "Gear_BurstGaugeAdditiveRate_Uncommon_MK2", 1 },
    ["gear_comboattackadditivedamage_common"] = { "Gear_ComboAttackAdditiveDamage_Common", 1 },
    ["gear_comboattackadditivedamage_common_mk2"] = { "Gear_ComboAttackAdditiveDamage_Common_MK2", 1 },
    ["gear_comboattackadditivedamage_rare"] = { "Gear_ComboAttackAdditiveDamage_Rare", 1 },
    ["gear_comboattackadditivedamage_rare_mk2"] = { "Gear_ComboAttackAdditiveDamage_Rare_MK2", 1 },
    ["gear_comboattackadditivedamage_uncommon"] = { "Gear_ComboAttackAdditiveDamage_Uncommon", 1 },
    ["gear_comboattackadditivedamage_uncommon_mk2"] = { "Gear_ComboAttackAdditiveDamage_Uncommon_MK2", 1 },
    ["gear_criticalpercentage_common"] = { "Gear_CriticalPercentage_Common", 1 },
    ["gear_criticalpercentage_common_mk2"] = { "Gear_CriticalPercentage_Common_MK2", 1 },
    ["gear_criticalpercentage_rare"] = { "Gear_CriticalPercentage_Rare", 1 },
    ["gear_criticalpercentage_rare_mk2"] = { "Gear_CriticalPercentage_Rare_MK2", 1 },
    ["gear_criticalpercentage_uncommon"] = { "Gear_CriticalPercentage_Uncommon", 1 },
    ["gear_criticalpercentage_uncommon_mk2"] = { "Gear_CriticalPercentage_Uncommon_MK2", 1 },
    ["gear_criticalvaluerate_common"] = { "Gear_CriticalValueRate_Common", 1 },
    ["gear_criticalvaluerate_common_mk2"] = { "Gear_CriticalValueRate_Common_MK2", 1 },
    ["gear_criticalvaluerate_rare"] = { "Gear_CriticalValueRate_Rare", 1 },
    ["gear_criticalvaluerate_rare_mk2"] = { "Gear_CriticalValueRate_Rare_MK2", 1 },
    ["gear_criticalvaluerate_uncommon"] = { "Gear_CriticalValueRate_Uncommon", 1 },
    ["gear_criticalvaluerate_uncommon_mk2"] = { "Gear_CriticalValueRate_Uncommon_MK2", 1 },
    ["gear_gainbetagaugevalueondamaged_common"] = { "Gear_GainBetaGaugeValueOnDamaged_Common", 1 },
    ["gear_gainbetagaugevalueondamaged_common_mk2"] = { "Gear_GainBetaGaugeValueOnDamaged_Common_MK2", 1 },
    ["gear_gainbetagaugevalueondamaged_rare"] = { "Gear_GainBetaGaugeValueOnDamaged_Rare", 1 },
    ["gear_gainbetagaugevalueondamaged_rare_mk2"] = { "Gear_GainBetaGaugeValueOnDamaged_Rare_MK2", 1 },
    ["gear_gainbetagaugevalueondamaged_uncommon"] = { "Gear_GainBetaGaugeValueOnDamaged_Uncommon", 1 },
    ["gear_gainbetagaugevalueondamaged_uncommon_mk2"] = { "Gear_GainBetaGaugeValueOnDamaged_Uncommon_MK2", 1 },
    ["gear_gainburstgaugevalueondamaged_common"] = { "Gear_GainBurstGaugeValueOnDamaged_Common", 1 },
    ["gear_gainburstgaugevalueondamaged_common_mk2"] = { "Gear_GainBurstGaugeValueOnDamaged_Common_MK2", 1 },
    ["gear_gainburstgaugevalueondamaged_rare"] = { "Gear_GainBurstGaugeValueOnDamaged_Rare", 1 },
    ["gear_gainburstgaugevalueondamaged_rare_mk2"] = { "Gear_GainBurstGaugeValueOnDamaged_Rare_MK2", 1 },
    ["gear_gainburstgaugevalueondamaged_uncommon"] = { "Gear_GainBurstGaugeValueOnDamaged_Uncommon", 1 },
    ["gear_gainburstgaugevalueondamaged_uncommon_mk2"] = { "Gear_GainBurstGaugeValueOnDamaged_Uncommon_MK2", 1 },
    ["gear_highhpdamageadditiverate_common"] = { "Gear_HighHpDamageAdditiveRate_Common", 1 },
    ["gear_highhpdamageadditiverate_common_mk2"] = { "Gear_HighHpDamageAdditiveRate_Common_MK2", 1 },
    ["gear_highhpdamageadditiverate_rare"] = { "Gear_HighHpDamageAdditiveRate_Rare", 1 },
    ["gear_highhpdamageadditiverate_rare_mk2"] = { "Gear_HighHpDamageAdditiveRate_Rare_MK2", 1 },
    ["gear_highhpdamageadditiverate_uncommon"] = { "Gear_HighHpDamageAdditiveRate_Uncommon", 1 },
    ["gear_highhpdamageadditiverate_uncommon_mk2"] = { "Gear_HighHpDamageAdditiveRate_Uncommon_MK2", 1 },
    ["gear_killenemyadditivedamagerate_common"] = { "Gear_KillEnemyAdditiveDamageRate_Common", 1 },
    ["gear_killenemyadditivedamagerate_common_mk2"] = { "Gear_KillEnemyAdditiveDamageRate_Common_MK2", 1 },
    ["gear_killenemyadditivedamagerate_rare"] = { "Gear_KillEnemyAdditiveDamageRate_Rare", 1 },
    ["gear_killenemyadditivedamagerate_rare_mk2"] = { "Gear_KillEnemyAdditiveDamageRate_Rare_MK2", 1 },
    ["gear_killenemyadditivedamagerate_uncommon"] = { "Gear_KillEnemyAdditiveDamageRate_Uncommon", 1 },
    ["gear_killenemyadditivedamagerate_uncommon_mk2"] = { "Gear_KillEnemyAdditiveDamageRate_Uncommon_MK2", 1 },
    ["gear_killenemyhealhp_common"] = { "Gear_KillEnemyHealHP_Common", 1 },
    ["gear_killenemyhealhp_common_mk2"] = { "Gear_KillEnemyHealHP_Common_MK2", 1 },
    ["gear_killenemyhealhp_rare"] = { "Gear_KillEnemyHealHP_Rare", 1 },
    ["gear_killenemyhealhp_rare_mk2"] = { "Gear_KillEnemyHealHP_Rare_MK2", 1 },
    ["gear_killenemyhealhp_uncommon"] = { "Gear_KillEnemyHealHP_Uncommon", 1 },
    ["gear_killenemyhealhp_uncommon_mk2"] = { "Gear_KillEnemyHealHP_Uncommon_MK2", 1 },
    ["gear_lowhpdamageadditiverate_common"] = { "Gear_LowHpDamageAdditiveRate_Common", 1 },
    ["gear_lowhpdamageadditiverate_common_mk2"] = { "Gear_LowHpDamageAdditiveRate_Common_MK2", 1 },
    ["gear_lowhpdamageadditiverate_rare"] = { "Gear_LowHpDamageAdditiveRate_Rare", 1 },
    ["gear_lowhpdamageadditiverate_rare_mk2"] = { "Gear_LowHpDamageAdditiveRate_Rare_MK2", 1 },
    ["gear_lowhpdamageadditiverate_uncommon"] = { "Gear_LowHpDamageAdditiveRate_Uncommon", 1 },
    ["gear_lowhpdamageadditiverate_uncommon_mk2"] = { "Gear_LowHpDamageAdditiveRate_Uncommon_MK2", 1 },
    ["gear_maxburstgauge_common"] = { "Gear_MaxBurstGauge_Common", 1 },
    ["gear_maxburstgauge_common_mk2"] = { "Gear_MaxBurstGauge_Common_MK2", 1 },
    ["gear_maxburstgauge_rare"] = { "Gear_MaxBurstGauge_Rare", 1 },
    ["gear_maxburstgauge_rare_mk2"] = { "Gear_MaxBurstGauge_Rare_MK2", 1 },
    ["gear_maxburstgauge_uncommon"] = { "Gear_MaxBurstGauge_Uncommon", 1 },
    ["gear_maxburstgauge_uncommon_mk2"] = { "Gear_MaxBurstGauge_Uncommon_MK2", 1 },
    ["gear_maxshield_common"] = { "Gear_MaxShield_Common", 1 },
    ["gear_maxshield_common_mk2"] = { "Gear_MaxShield_Common_MK2", 1 },
    ["gear_maxshield_rare"] = { "Gear_MaxShield_Rare", 1 },
    ["gear_maxshield_rare_mk2"] = { "Gear_MaxShield_Rare_MK2", 1 },
    ["gear_maxshield_uncommon"] = { "Gear_MaxShield_Uncommon", 1 },
    ["gear_maxshield_uncommon_mk2"] = { "Gear_MaxShield_Uncommon_MK2", 1 },
    ["gear_meleeattackdamagereductionrate_common"] = { "Gear_MeleeAttackDamageReductionRate_Common", 1 },
    ["gear_meleeattackdamagereductionrate_common_mk2"] = { "Gear_MeleeAttackDamageReductionRate_Common_MK2", 1 },
    ["gear_meleeattackdamagereductionrate_rare"] = { "Gear_MeleeAttackDamageReductionRate_Rare", 1 },
    ["gear_meleeattackdamagereductionrate_rare_mk2"] = { "Gear_MeleeAttackDamageReductionRate_Rare_MK2", 1 },
    ["gear_meleeattackdamagereductionrate_uncommon"] = { "Gear_MeleeAttackDamageReductionRate_Uncommon", 1 },
    ["gear_meleeattackdamagereductionrate_uncommon_mk2"] = { "Gear_MeleeAttackDamageReductionRate_Uncommon_MK2", 1 },
    ["gear_meleerangedamagereductionrate_common"] = { "Gear_MeleeRangeDamageReductionRate_Common", 1 },
    ["gear_meleerangedamagereductionrate_common_mk2"] = { "Gear_MeleeRangeDamageReductionRate_Common_MK2", 1 },
    ["gear_meleerangedamagereductionrate_rare"] = { "Gear_MeleeRangeDamageReductionRate_Rare", 1 },
    ["gear_meleerangedamagereductionrate_rare_mk2"] = { "Gear_MeleeRangeDamageReductionRate_Rare_MK2", 1 },
    ["gear_meleerangedamagereductionrate_uncommon"] = { "Gear_MeleeRangeDamageReductionRate_Uncommon", 1 },
    ["gear_meleerangedamagereductionrate_uncommon_mk2"] = { "Gear_MeleeRangeDamageReductionRate_Uncommon_MK2", 1 },
    ["gear_rangeattackdamageadditiverate_common"] = { "Gear_RangeAttackDamageAdditiveRate_Common", 1 },
    ["gear_rangeattackdamageadditiverate_common_mk2"] = { "Gear_RangeAttackDamageAdditiveRate_Common_MK2", 1 },
    ["gear_rangeattackdamageadditiverate_rare"] = { "Gear_RangeAttackDamageAdditiveRate_Rare", 1 },
    ["gear_rangeattackdamageadditiverate_rare_mk2"] = { "Gear_RangeAttackDamageAdditiveRate_Rare_MK2", 1 },
    ["gear_rangeattackdamageadditiverate_uncommon"] = { "Gear_RangeAttackDamageAdditiveRate_Uncommon", 1 },
    ["gear_rangeattackdamageadditiverate_uncommon_mk2"] = { "Gear_RangeAttackDamageAdditiveRate_Uncommon_MK2", 1 },
    ["gear_rangeattackdamagereductionrate_common"] = { "Gear_RangeAttackDamageReductionRate_Common", 1 },
    ["gear_rangeattackdamagereductionrate_common_mk2"] = { "Gear_RangeAttackDamageReductionRate_Common_MK2", 1 },
    ["gear_rangeattackdamagereductionrate_rare"] = { "Gear_RangeAttackDamageReductionRate_Rare", 1 },
    ["gear_rangeattackdamagereductionrate_rare_mk2"] = { "Gear_RangeAttackDamageReductionRate_Rare_MK2", 1 },
    ["gear_rangeattackdamagereductionrate_uncommon"] = { "Gear_RangeAttackDamageReductionRate_Uncommon", 1 },
    ["gear_rangeattackdamagereductionrate_uncommon_mk2"] = { "Gear_RangeAttackDamageReductionRate_Uncommon_MK2", 1 },
    ["gear_spexpadditiverate_common"] = { "Gear_SPExpAdditiveRate_Common", 1 },
    ["gear_spexpadditiverate_common_mk2"] = { "Gear_SPExpAdditiveRate_Common_MK2", 1 },
    ["gear_spexpadditiverate_rare"] = { "Gear_SPExpAdditiveRate_Rare", 1 },
    ["gear_spexpadditiverate_rare_mk2"] = { "Gear_SPExpAdditiveRate_Rare_MK2", 1 },
    ["gear_spexpadditiverate_uncommon"] = { "Gear_SPExpAdditiveRate_Uncommon", 1 },
    ["gear_spexpadditiverate_uncommon_mk2"] = { "Gear_SPExpAdditiveRate_Uncommon_MK2", 1 },
    ["gear_shieldattackpowerrate_common"] = { "Gear_ShieldAttackPowerRate_Common", 1 },
    ["gear_shieldattackpowerrate_common_mk2"] = { "Gear_ShieldAttackPowerRate_Common_MK2", 1 },
    ["gear_shieldattackpowerrate_rare"] = { "Gear_ShieldAttackPowerRate_Rare", 1 },
    ["gear_shieldattackpowerrate_rare_mk2"] = { "Gear_ShieldAttackPowerRate_Rare_MK2", 1 },
    ["gear_shieldattackpowerrate_uncommon"] = { "Gear_ShieldAttackPowerRate_Uncommon", 1 },
    ["gear_shieldattackpowerrate_uncommon_mk2"] = { "Gear_ShieldAttackPowerRate_Uncommon_MK2", 1 },
    ["gear_shieldignorepercentage_common"] = { "Gear_ShieldIgnorePercentage_Common", 1 },
    ["gear_shieldignorepercentage_common_mk2"] = { "Gear_ShieldIgnorePercentage_Common_MK2", 1 },
    ["gear_shieldignorepercentage_rare"] = { "Gear_ShieldIgnorePercentage_Rare", 1 },
    ["gear_shieldignorepercentage_rare_mk2"] = { "Gear_ShieldIgnorePercentage_Rare_MK2", 1 },
    ["gear_shieldignorepercentage_uncommon"] = { "Gear_ShieldIgnorePercentage_Uncommon", 1 },
    ["gear_shieldignorepercentage_uncommon_mk2"] = { "Gear_ShieldIgnorePercentage_Uncommon_MK2", 1 },
    ["hp_potion"] = { "HP_Potion", 99 },
    ["hp_potion_small"] = { "HP_Potion_Small", 99 },
    ["hair_000"] = { "Hair_000", 1 },
    ["hair_001"] = { "Hair_001", 1 },
    ["hair_002"] = { "Hair_002", 1 },
    ["hair_003"] = { "Hair_003", 1 },
    ["hair_004"] = { "Hair_004", 1 },
    ["hair_005"] = { "Hair_005", 1 },
    ["hair_006"] = { "Hair_006", 1 },
    ["hair_007"] = { "Hair_007", 1 },
    ["hair_008"] = { "Hair_008", 1 },
    ["hair_009"] = { "Hair_009", 1 },
    ["hair_010"] = { "Hair_010", 1 },
    ["hair_011"] = { "Hair_011", 1 },
    ["hair_012"] = { "Hair_012", 1 },
    ["hair_christmas_01"] = { "Hair_Christmas_01", 1 },
    ["hair_shorttail"] = { "Hair_ShortTail", 1 },
    ["healgrenade"] = { "HealGrenade", 99 },
    ["highdensitywafer"] = { "HighDensityWafer", 99 },
    ["item_fish_slice_bait"] = { "Item_Fish_Slice_Bait", 99 },
    ["item_lure_megabait"] = { "Item_Lure_Megabait", 99 },
    ["item_lure_weird"] = { "Item_Lure_Weird", 99 },
    ["item_records_atl_memory_04"] = { "Item_Records_ATL_Memory_04", 1 },
    ["item_records_ded40_memory_11"] = { "Item_Records_DED40_Memory_11", 1 },
    ["item_records_day1_memory_02"] = { "Item_Records_Day1_Memory_02", 1 },
    ["item_records_day1_memory_03"] = { "Item_Records_Day1_Memory_03", 1 },
    ["item_records_etc_memory_08"] = { "Item_Records_ETC_Memory_08", 1 },
    ["item_records_etc_memory_10"] = { "Item_Records_ETC_Memory_10", 1 },
    ["item_records_etc_memory_12"] = { "Item_Records_ETC_Memory_12", 1 },
    ["item_records_me01_memory_07"] = { "Item_Records_ME01_Memory_07", 1 },
    ["item_records_me04_memory_15"] = { "Item_Records_ME04_Memory_15", 1 },
    ["item_records_se06_memory_11"] = { "Item_Records_SE06_Memory_11", 1 },
    ["item_records_wla_memory_29"] = { "Item_Records_WLA_Memory_29", 1 },
    ["item_records_wla_memory_31"] = { "Item_Records_WLA_Memory_31", 1 },
    ["item_records_wla_memory_34"] = { "Item_Records_WLA_Memory_34", 1 },
    ["item_records_wlb_memory_40"] = { "Item_Records_WLB_Memory_40", 1 },
    ["item_records_wlb_memory_41"] = { "Item_Records_WLB_Memory_41", 1 },
    ["item_records_xion_memory_01"] = { "Item_Records_Xion_Memory_01", 1 },
    ["item_records_xion_memory_03"] = { "Item_Records_Xion_Memory_03", 1 },
    ["item_records_xion_memory_04"] = { "Item_Records_Xion_Memory_04", 1 },
    ["item_records_xion_memory_05"] = { "Item_Records_Xion_Memory_05", 1 },
    ["item_records_xion_memory_06"] = { "Item_Records_Xion_Memory_06", 1 },
    ["item_records_xion_memory_07"] = { "Item_Records_Xion_Memory_07", 1 },
    ["item_records_xion_memory_08"] = { "Item_Records_Xion_Memory_08", 1 },
    ["item_records_xion_memory_16"] = { "Item_Records_Xion_Memory_16", 1 },
    ["item_records_xion_memory_17"] = { "Item_Records_Xion_Memory_17", 1 },
    ["item_records_xion_memory_18"] = { "Item_Records_Xion_Memory_18", 1 },
    ["item_records_xion_memory_21"] = { "Item_Records_Xion_Memory_21", 1 },
    ["item_records_xion_memory_22"] = { "Item_Records_Xion_Memory_22", 1 },
    ["item_records_xion_memory_23"] = { "Item_Records_Xion_Memory_23", 1 },
    ["item_records_xion_memory_24"] = { "Item_Records_Xion_Memory_24", 1 },
    ["item_records_xion_memory_25"] = { "Item_Records_Xion_Memory_25", 1 },
    ["item_records_xion_memory_29"] = { "Item_Records_Xion_Memory_29", 1 },
    ["item_shrimp_bait"] = { "Item_Shrimp_Bait", 99 },
    ["item_special_bait"] = { "Item_Special_Bait", 99 },
    ["item_worm_bait"] = { "Item_Worm_Bait", 99 },
    ["lilycostume_001"] = { "LilyCostume_001", 1 },
    ["lilycostume_003"] = { "LilyCostume_003", 1 },
    ["lilycostume_003_var2"] = { "LilyCostume_003_Var2", 1 },
    ["lilycostume_004"] = { "LilyCostume_004", 1 },
    ["lilycostume_004_var2"] = { "LilyCostume_004_Var2", 1 },
    ["lowdensitywafer"] = { "LowDensityWafer", 99 },
    ["money_junkiron_a"] = { "Money_JunkIron_A", 9999 },
    ["money_junkiron_b"] = { "Money_JunkIron_B", 9999 },
    ["money_junkiron_c"] = { "Money_JunkIron_C", 9999 },
    ["pt_burst"] = { "PT_Burst", 1 },
    ["pt_burst_mk2"] = { "PT_Burst_MK2", 1 },
    ["pt_combo"] = { "PT_Combo", 1 },
    ["pt_combo_mk2"] = { "PT_Combo_MK2", 1 },
    ["pt_crowd"] = { "PT_Crowd", 1 },
    ["pt_crowd_mk2"] = { "PT_Crowd_MK2", 1 },
    ["pt_down"] = { "PT_Down", 1 },
    ["pt_down_mk2"] = { "PT_Down_MK2", 1 },
    ["pt_grenade"] = { "PT_Grenade", 1 },
    ["pt_grenade_mk2"] = { "PT_Grenade_MK2", 1 },
    ["pt_guard"] = { "PT_Guard", 1 },
    ["pt_guard_mk2"] = { "PT_Guard_MK2", 1 },
    ["pt_recovery"] = { "PT_Recovery", 1 },
    ["pt_recovery_mk2"] = { "PT_Recovery_MK2", 1 },
    ["pt_shoot"] = { "PT_Shoot", 1 },
    ["pt_shoot_mk2"] = { "PT_Shoot_MK2", 1 },
    ["pt_skill"] = { "PT_Skill", 1 },
    ["pt_skill_mk2"] = { "PT_Skill_MK2", 1 },
    ["pt_stab"] = { "PT_Stab", 1 },
    ["pt_stab_mk2"] = { "PT_Stab_MK2", 1 },
    ["pt_survive"] = { "PT_Survive", 1 },
    ["pt_survive_mk2"] = { "PT_Survive_MK2", 1 },
    ["pt_tachy"] = { "PT_Tachy", 1 },
    ["pt_tachy_mk2"] = { "PT_Tachy_MK2", 1 },
    ["polymerorganicfilm"] = { "PolymerOrganicFilm", 99 },
    ["pulsegrenade"] = { "PulseGrenade", 99 },
    ["recovery_hp_potion"] = { "Recovery_HP_Potion", 99 },
    ["resurrectionitem"] = { "ResurrectionItem", 99 },
    ["spinitializer"] = { "SPInitializer", 99 },
    ["trapgrenade"] = { "TrapGrenade", 99 },
    ["tumblercore"] = { "TumblerCore", 99 },
    ["turntablemusicbundle"] = { "TurntableMusicBundle", 1 },
    ["turntablemusicbundle2"] = { "TurntableMusicBundle2", 1 },
    ["weaponcore"] = { "WeaponCore", 99 },
    ["weaponcore_damaged"] = { "WeaponCore_Damaged", 99 },
}
-- @@GENERATED_ALLOWLIST_END@@

local function trim(value)
    return tostring(value or ""):match("^%s*(.-)%s*$") or ""
end

local function readKeyValueFile(path)
    local values = {}
    local f = io.open(path, "r")
    if not f then return nil end
    for line in f:lines() do
        local key, value = line:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
        if key then values[key] = value end
    end
    f:close()
    return values
end

local function publishAtomic(path, body)
    local temporary = path .. ".tmp"
    local f = io.open(temporary, "w")
    if not f then return false, "temporary_file_open_failed" end
    f:write(body)
    f:close()
    os.remove(path)
    local ok, err = os.rename(temporary, path)
    if not ok then
        os.remove(temporary)
        return false, "atomic_publish_failed:" .. tostring(err)
    end
    return true, "published"
end

local function safeHexToken(value)
    value = trim(value)
    return #value >= 32 and #value <= 64 and value:match("^[A-Fa-f0-9]+$") ~= nil
end

-- Baseline the durable panel sequence before readiness is ever published. A
-- bridge reload therefore consumes no prior request.
local initialState = readKeyValueFile(STATE_FILE) or {}
local initialStatus = readKeyValueFile(STATUS_FILE) or {}
local lastSpawnSeq = tonumber(initialState.spawnseq or "0") or 0
local initialAlias = trim(initialState.spawnalias)
local initialEntry = APPROVED_ALIASES[initialAlias:lower()]
local initialCanonicalAlias = initialEntry and initialEntry[1] or nil
local initialSession = trim(initialState.spawnsession)
local initialRequestId = trim(initialState.spawnrequest)
local initialSequence = math.floor(tonumber(initialState.spawnseq or "0") or 0)
local initialStatusMatches = initialStatus.spawnsession == initialSession
    and initialStatus.spawnrequest == initialRequestId
    and tonumber(initialStatus.spawnseq or "0") == initialSequence
    and initialStatus.itemalias == initialCanonicalAlias
local recoveryRequest = nil
if initialState.spawnmode == "inventory"
    and initialSequence > 0
    and safeHexToken(initialSession)
    and safeHexToken(initialRequestId)
    and initialCanonicalAlias
    and (not initialStatusMatches or initialStatus.pending ~= "0")
then
    recoveryRequest = {
        alias = initialCanonicalAlias,
        panelSeq = initialSequence,
        session = initialSession,
        requestId = initialRequestId,
        unknownPublished = false,
    }
end
local loopBeat = 0
local activeRequest = recoveryRequest ~= nil
local activeNativeRequestPublished = recoveryRequest ~= nil
local requestGeneration = 0
local nativeSession = ""
local nativeBeat = 0
local nativeStaleTicks = NATIVE_STALE_TICKS + 1
local nativeAdvanceConfirmed = false
local nativeReady = false

local function writeStatus(ok, pending, message, detail, alias, panelSeq, session, requestId)
    local body = table.concat({
        "ok=" .. (ok and "1" or "0"),
        "pending=" .. (pending and "1" or "0"),
        "spawnapi=" .. SPAWN_API,
        "spawnseq=" .. tostring(panelSeq or 0),
        "spawnsession=" .. trim(session),
        "spawnrequest=" .. trim(requestId),
        "itemalias=" .. trim(alias),
        "message=" .. trim(message):gsub("[\r\n]", " "),
        "detail=" .. trim(detail):gsub("[\r\n]", " "),
        "",
    }, "\n")
    publishAtomic(STATUS_FILE, body)
end

local function refreshNativeReadiness()
    local heartbeat = readKeyValueFile(NATIVE_HEARTBEAT_FILE)
    if not heartbeat
        or heartbeat.protocol ~= SPAWN_API
        or heartbeat.module ~= NATIVE_MODULE
        or heartbeat.ready ~= "1"
        or not safeHexToken(heartbeat.session)
    then
        nativeReady = false
        nativeAdvanceConfirmed = false
        nativeStaleTicks = NATIVE_STALE_TICKS + 1
        return
    end

    local nextSession = trim(heartbeat.session)
    local nextBeat = math.floor(tonumber(heartbeat.beat or "0") or 0)
    local bucket = tonumber(heartbeat.inventory_bucket_guid or "0") or 0
    local target = tonumber(heartbeat.inventory_target_guid or "0") or 0
    if nextBeat <= 0 or bucket <= 0 or target <= 0 then
        nativeReady = false
        return
    end

    if nextSession ~= nativeSession then
        requestGeneration = requestGeneration + 1
        nativeSession = nextSession
        nativeBeat = nextBeat
        nativeStaleTicks = 0
        nativeAdvanceConfirmed = false
        nativeReady = false
        local recoveringThisSession = recoveryRequest
            and recoveryRequest.session == nextSession
        activeRequest = recoveringThisSession and true or false
        activeNativeRequestPublished = recoveringThisSession and true or false
        if not recoveringThisSession then recoveryRequest = nil end
        return
    end

    if nextBeat > nativeBeat then
        nativeBeat = nextBeat
        nativeStaleTicks = 0
        nativeAdvanceConfirmed = true
    elseif nextBeat == nativeBeat then
        nativeStaleTicks = nativeStaleTicks + 1
    else
        nativeBeat = nextBeat
        nativeStaleTicks = NATIVE_STALE_TICKS + 1
        nativeAdvanceConfirmed = false
    end
    nativeReady = nativeAdvanceConfirmed and nativeStaleTicks <= NATIVE_STALE_TICKS
end

local function writeHeartbeat(lastAction)
    loopBeat = loopBeat + 1
    local body = table.concat({
        "beat=" .. tostring(loopBeat),
        "last=" .. tostring(lastAction or "idle"),
        "spawnseq=" .. tostring(lastSpawnSeq),
        "cheatmanager=" .. (nativeReady and "1" or "0"),
        "eve=" .. (nativeReady and "1" or "0"),
        "spawnapi=" .. SPAWN_API,
        "bridge=" .. BRIDGE_ID,
        "session=" .. (nativeReady and nativeSession or ""),
        "nativebeat=" .. (nativeReady and tostring(nativeBeat) or "0"),
        "requestpending=" .. (activeRequest and "1" or "0"),
        "",
    }, "\n")
    publishAtomic(HEARTBEAT_FILE, body)
end

local function panelRequestIsFresh(panelIssuedUnixSeconds, currentUnixSeconds)
    if panelIssuedUnixSeconds <= 0 then return false end
    if panelIssuedUnixSeconds > currentUnixSeconds + 1 then return false end
    local requestAge = panelIssuedUnixSeconds <= currentUnixSeconds
        and (currentUnixSeconds - panelIssuedUnixSeconds) or 0
    return requestAge < PANEL_REQUEST_MAX_AGE_SECONDS
end

local function writeNativeRequest(
    panelSeq, session, requestId, alias, aliasIndex, quantity, panelIssuedUnixSeconds
)
    os.remove(NATIVE_RESULT_FILE)
    local body = table.concat({
        "protocol=" .. SPAWN_API,
        "bridge=" .. BRIDGE_ID,
        "session=" .. session,
        "request_id=" .. requestId,
        "panel_seq=" .. tostring(panelSeq),
        "issued_unix_s=" .. tostring(panelIssuedUnixSeconds),
        "native_beat=" .. tostring(nativeBeat),
        "alias=" .. alias,
        "alias_index=" .. tostring(aliasIndex),
        "qty=" .. tostring(quantity),
        "",
    }, "\n")
    return publishAtomic(NATIVE_REQUEST_FILE, body)
end

local function getFNameComparisonIndex(alias)
    local itemName = UEHelpers.FindOrAddFName(alias)
    if not itemName then return nil, "fname_not_created" end
    local index = nil
    local ok, err = pcall(function()
        index = itemName:GetComparisonIndex()
    end)
    if not ok then return nil, "fname_index_failed:" .. tostring(err) end
    index = tonumber(index)
    if not index or index <= 0 or index > 0xFFFFFFFF then
        return nil, "fname_index_invalid:" .. tostring(index)
    end
    return math.floor(index), nil
end

-- v4: a native result that is not "ok" gets a plain sentence. A side effect
-- (another watched item changed with the add) locks the native session.
local function failureMessage(status)
    if status == "side_effect_detected" then
        return "Another item changed with this add. Live Add is locked until the game restarts; check the inventory."
    end
    return "The item was not added."
end

local function finishRequest(ok, message, detail, alias, panelSeq, session, requestId)
    activeRequest = false
    activeNativeRequestPublished = false
    recoveryRequest = nil
    writeStatus(ok, false, message, detail, alias, panelSeq, session, requestId)
end

local function pollRecoveredRequest()
    local request = recoveryRequest
    if not request or not activeRequest or request.session ~= nativeSession then return end
    local result = readKeyValueFile(NATIVE_RESULT_FILE)
    local matches = result
        and result.protocol == SPAWN_API
        and result.session == request.session
        and result.request_id == request.requestId
        and tonumber(result.panel_seq or "0") == request.panelSeq
    if not matches then return end
    if result.terminal ~= "1" then
        if not request.unknownPublished then
            request.unknownPublished = true
            writeStatus(false, true,
                "The game did not provide a final confirmation. Restart the game and check the item before retrying.",
                "native_live_add:recovered_outcome_unknown reason=" .. tostring(result.detail or "unconfirmed"),
                request.alias, request.panelSeq, request.session, request.requestId)
        end
        return
    end
    if result.status == "ok" then
        local before = tonumber(result.before) or 0
        local after = tonumber(result.after) or before
        finishRequest(true, "Added the selected item.",
            string.format(
                "native_live_add:recovered_verified panel_seq=%d request=%s bucket=%s before=%d after=%d | persistence:not_verified",
                request.panelSeq, request.requestId, tostring(result.bucket_guid or "0"), before, after
            ),
            request.alias, request.panelSeq, request.session, request.requestId)
    else
        finishRequest(false, failureMessage(result.status),
            "native_live_add:" .. tostring(result.detail or "native_request_failed"),
            request.alias, request.panelSeq, request.session, request.requestId)
    end
    writeHeartbeat("spawn-recovered-result")
end

local function startLiveAdd(
    alias, quantity, panelSeq, session, requestId, panelIssuedUnixSeconds
)
    requestGeneration = requestGeneration + 1
    local generation = requestGeneration
    activeNativeRequestPublished = false
    if not nativeReady or session ~= nativeSession then
        finishRequest(false, "Live Add is waiting for a fresh game session.",
            "native_live_add:session_not_ready", alias, panelSeq, session, requestId)
        return
    end
    if not panelRequestIsFresh(panelIssuedUnixSeconds, os.time()) then
        finishRequest(false, "Live Add rejected an expired item request.",
            "policy:request_expired_before_game_thread_work",
            alias, panelSeq, session, requestId)
        return
    end

    local aliasIndex, indexError = getFNameComparisonIndex(alias)
    if not aliasIndex then
        finishRequest(false, "The selected item could not be prepared safely.",
            "native_live_add:" .. tostring(indexError), alias, panelSeq, session, requestId)
        return
    end
    if not panelRequestIsFresh(panelIssuedUnixSeconds, os.time()) then
        finishRequest(false, "Live Add rejected an expired item request.",
            "policy:request_expired_before_native_publication",
            alias, panelSeq, session, requestId)
        return
    end

    local wrote, writeDetail = writeNativeRequest(
        panelSeq, session, requestId, alias, aliasIndex, quantity,
        panelIssuedUnixSeconds
    )
    if not wrote then
        finishRequest(false, "The inventory request could not be sent safely.",
            "native_live_add:" .. tostring(writeDetail), alias, panelSeq, session, requestId)
        return
    end
    activeNativeRequestPublished = true

    local pendingDetail = string.format(
        "native_live_add:pending panel_seq=%d request=%s alias_index=%d qty=%d",
        panelSeq, requestId, aliasIndex, quantity
    )
    writeStatus(false, true, "Adding the selected item...", pendingDetail,
        alias, panelSeq, session, requestId)

    local attempts = 0
    local function pollResult()
        if generation ~= requestGeneration or not activeRequest then return end
        attempts = attempts + 1
        local result = readKeyValueFile(NATIVE_RESULT_FILE)
        local matches = result
            and result.protocol == SPAWN_API
            and result.session == session
            and result.request_id == requestId
            and tonumber(result.panel_seq or "0") == panelSeq
        if matches then
            if result.terminal ~= "1" then
                writeStatus(false, true,
                    "The game did not provide a final confirmation. Restart the game and check the item before retrying.",
                    "native_live_add:outcome_unknown reason=" .. tostring(result.detail or "unconfirmed"),
                    alias, panelSeq, session, requestId)
                writeHeartbeat("spawn-outcome-unknown")
                return
            end
            if result.status == "ok" then
                local before = tonumber(result.before) or 0
                local after = tonumber(result.after) or before
                finishRequest(true, "Added the selected item.",
                    string.format(
                        "native_live_add:verified panel_seq=%d request=%s bucket=%s before=%d after=%d | persistence:not_verified",
                        panelSeq, requestId, tostring(result.bucket_guid or "0"), before, after
                    ),
                    alias, panelSeq, session, requestId)
            else
                local reason = tostring(result.detail or "native_request_failed")
                finishRequest(false, failureMessage(result.status),
                    "native_live_add:" .. reason, alias, panelSeq, session, requestId)
            end
            writeHeartbeat("spawn-result")
            return
        end

        if attempts >= 64 then
            if attempts == 64 then
                writeStatus(false, true,
                    "Still waiting for the game to confirm the item. Do not retry yet.",
                    pendingDetail .. " | waiting_for_exact_result",
                    alias, panelSeq, session, requestId)
                writeHeartbeat("spawn-waiting")
            end
            ExecuteWithDelay(500, pollResult)
            return
        end
        ExecuteWithDelay(125, pollResult)
    end
    ExecuteWithDelay(125, pollResult)
end

local function dispatchState(state)
    local spawnSeq = math.floor(tonumber(state.spawnseq or "0") or 0)
    if spawnSeq <= 0 or spawnSeq == lastSpawnSeq then return end
    lastSpawnSeq = spawnSeq

    local mode = trim(state.spawnmode)
    local requestedAlias = trim(state.spawnalias)
    local entry = APPROVED_ALIASES[requestedAlias:lower()]
    local canonicalAlias = entry and entry[1] or nil
    local quantityText = trim(state.spawnqty)
    local quantity = nil
    if quantityText:match("^[1-9][0-9]*$") and #quantityText <= 7 then
        quantity = math.floor(tonumber(quantityText))
    end
    local session = trim(state.spawnsession)
    local requestId = trim(state.spawnrequest)
    local panelIssuedUnixSeconds = math.floor(tonumber(state.spawnissuedunixs or "0") or 0)
    local bridgeUnixSeconds = os.time()

    if mode ~= "inventory" then
        writeStatus(false, false, "Live Add rejected an unsupported command.",
            "policy:mode_blocked", requestedAlias, spawnSeq, session, requestId)
        return
    end
    if not safeHexToken(session) or session ~= nativeSession or not nativeReady then
        writeStatus(false, false, "Live Add rejected a stale game session.",
            "policy:session_blocked", requestedAlias, spawnSeq, session, requestId)
        return
    end
    if not safeHexToken(requestId) then
        writeStatus(false, false, "Live Add rejected an invalid request.",
            "policy:request_blocked", requestedAlias, spawnSeq, session, requestId)
        return
    end
    if not panelRequestIsFresh(panelIssuedUnixSeconds, bridgeUnixSeconds) then
        writeStatus(false, false, "Live Add rejected an expired item request.",
            "policy:request_expired", requestedAlias, spawnSeq, session, requestId)
        return
    end
    if not requestedAlias:match("^[%w_+]+$") or #requestedAlias > 128 then
        writeStatus(false, false, "Live Add rejected an invalid item identifier.",
            "policy:invalid_alias", requestedAlias, spawnSeq, session, requestId)
        return
    end
    if not canonicalAlias then
        writeStatus(false, false, "This item is not in the verified Live Add catalog.",
            "policy:alias_blocked", requestedAlias, spawnSeq, session, requestId)
        return
    end
    if not quantity or quantity < 1 or quantity > entry[2] then
        writeStatus(false, false, "This amount is not allowed for this item.",
            "policy:quantity_blocked max=" .. tostring(entry[2]), canonicalAlias, spawnSeq, session, requestId)
        return
    end
    if activeRequest then
        writeStatus(false, false, "Live Add is already finishing another item.",
            "policy:request_in_flight", requestedAlias, spawnSeq, session, requestId)
        return
    end

    activeRequest = true
    ExecuteInGameThread(function()
        local ok, err = pcall(
            startLiveAdd, canonicalAlias, quantity, spawnSeq, session, requestId,
            panelIssuedUnixSeconds
        )
        if not ok then
            if activeNativeRequestPublished then
                writeStatus(false, true,
                    "The item request needs a game restart before it can be retried.",
                    "native_live_add:outcome_unknown lua_exception:" .. tostring(err),
                    canonicalAlias, spawnSeq, session, requestId)
            else
                finishRequest(false, "Live Add stopped safely.",
                    "native_live_add:lua_exception:" .. tostring(err),
                    canonicalAlias, spawnSeq, session, requestId)
            end
        end
        writeHeartbeat("spawn-dispatched")
    end)
end

LoopAsync(250, function()
    local ok, err = pcall(function()
        refreshNativeReadiness()
        pollRecoveredRequest()
        local state = readKeyValueFile(STATE_FILE)
        if state then dispatchState(state) end
        writeHeartbeat("idle")
    end)
    if not ok then
        if activeRequest then
            writeStatus(false, true,
                "The current item request is still locked while Live Add recovers.",
                "bridge:loop_exception_outcome_unknown:" .. tostring(err), "", 0, "", "")
        else
            writeStatus(false, false, "Live Add paused after a safe bridge error.",
                "bridge:loop_exception:" .. tostring(err), "", 0, "", "")
        end
    end
    return false
end)

print("[SBLiveAddBridge] Loaded fail-closed Live Add v4 bridge; waiting for dedicated SBLiveAddNative 0.5.0.\n")
writeHeartbeat("loaded")
